name: Laravel

on:
  pull_request:
    branches: ["main"]

jobs:
  laravel-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - uses: actions/checkout@v4
      - name: Prepare Laravel Application
        run: |
          cp .env.testing .env
          php artisan key:generate
          php artisan migrate
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Generate key
        run: php artisan key:generate
      - name: Larastan
        run: ./vendor/bin/phpstan analyse
      - name: Pint
        run: ./vendor/bin/pint --test
      - name: npm install
        run: npm ci
      - name: npm run build
        run: npm run build
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        run: php artisan test
